version: 0.1.{build}

image:
  - Ubuntu
  - Visual Studio 2017
configuration:
  - Release
for:
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - sh: >-
          echo ---- build for Linux! ----

          pwd

          dotnet --info

          cd demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin/Release/NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ../../modify-test-case-packages.patch

          dotnet build -c Debug

    test_script:
      - sh: >-
          echo ---- test for Linux! ----

          pwd

          cd ../../NuLink.TestCase.Consumer

          dotnet build

          cat NuLink.TestCase.ConsumerLib/obj/NuLink.TestCase.ConsumerLib.csproj.nuget.g.props

          dotnet test

  -
    matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - ps: >-
          write-host "---- build for Windows! ----"

          write-host(Get-Location)

          dotnet --info

          cd demos\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin\Release\NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ..\..\modify-test-case-packages.patch

          dotnet build -c Debug

    test_script:
      - ps: >-
          write-host "---- test for Windows! ----"

          write-host(Get-Location)

          cd ..\..\NuLink.TestCase.Consumer

          dotnet build

          dotnet test
