version: 0.1.0-0.ci.{build}

skip_commits:
  files:
    - docs/*
    - '**/*.md'

image:
  - Ubuntu
  - Visual Studio 2017

configuration:
  - Release

for:
  -
    matrix:
      only:
        - image: Ubuntu
    dotnet_csproj:
      patch: true
      file: 'source/**/*.csproj'
      version: '{version}'
    build_script:
      - sh: >-
          cd $APPVEYOR_BUILD_FOLDER/source

          dotnet restore

          dotnet build -c Release

          appveyor PushArtifact NuLink.Cli/bin/Release/NuLink.$APPVEYOR_BUILD_VERSION.nupkg

    before_test:
      - sh: >-
          echo ---- before_test for Linux! ----

          pwd

          dotnet --info

          cd $APPVEYOR_BUILD_FOLDER/demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin/Release/NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ../../modify-test-case-packages.patch

          dotnet build -c Debug

    test_script:
      - sh: >-
          echo ---- test for Linux! ----

          dotnet tool install -g NuLink --version $APPVEYOR_BUILD_VERSION --add-source https://ci.appveyor.com/nuget/nulink-3672eibylf8q 

          nulink --version

          pwd

          cd $APPVEYOR_BUILD_FOLDER/demos/NuLink.TestCase.Consumer

          dotnet restore

          nulink link -p NuLink.TestCase.FirstPackage -l $APPVEYOR_BUILD_FOLDER/demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage.csproj

          dotnet build

          cat NuLink.TestCase.ConsumerLib/obj/NuLink.TestCase.ConsumerLib.csproj.nuget.g.props

          dotnet test

  -
    matrix:
      only:
        - image: Visual Studio 2017
    dotnet_csproj:
      patch: true
      file: 'source\**\*.csproj'
      version: '{version}'
    before_build:
      - cmd: >-
          cd %APPVEYOR_BUILD_FOLDER%\source

          dotnet restore

          dotnet build -c Release

          appveyor PushArtifact NuLink.Cli\bin\Release\NuLink.%APPVEYOR_BUILD_VERSION%.nupkg

    before_test:
      - cmd: >-
          echo ---- before_test for Windows! ----

          echo %cd%

          dotnet --info

          cd %APPVEYOR_BUILD_FOLDER%\demos\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin\Release\NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ..\..\modify-test-case-packages.patch

          dotnet build -c Debug

    test_script:
      - cmd: >-
          echo ---- test for Windows! ----

          echo USER-PROFILE: %UserProfile%

          dotnet tool install -g NuLink --version %APPVEYOR_BUILD_VERSION% --add-source https://ci.appveyor.com/nuget/nulink-3672eibylf8q 

          nulink --version

          echo %cd%

          cd %APPVEYOR_BUILD_FOLDER%\demos\NuLink.TestCase.Consumer

          dotnet restore

          nulink link -p NuLink.TestCase.FirstPackage -l %APPVEYOR_BUILD_FOLDER%\demos\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage.csproj

          dotnet build

          type NuLink.TestCase.ConsumerLib\obj\NuLink.TestCase.ConsumerLib.csproj.nuget.g.props

          dotnet test
