version: 0.1.{build}

image:
  - Ubuntu
  - Visual Studio 2017
configuration:
  - Release
for:
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - sh: >-
          echo ---- build for Linux! ----

          pwd

          dotnet --info

          cd demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin/Release/NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ../../modify-test-case-packages.patch

          dotnet build -c Debug

          cd $APPVEYOR_BUILD_FOLDER/source/NuLink.Cli

          dotnet build -c Release

    test_script:
      - sh: >-
          echo ---- test for Linux! ----

          pwd

          cd $APPVEYOR_BUILD_FOLDER/demos/NuLink.TestCase.Consumer

          dotnet restore

          dotnet $APPVEYOR_BUILD_FOLDER/source/NuLink.Cli/bin/Release/netcoreapp2.1/dotnet-nulink.dll link -p NuLink.TestCase.FirstPackage -l $APPVEYOR_BUILD_FOLDER/demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage.csproj

          dotnet build

          cat NuLink.TestCase.ConsumerLib/obj/NuLink.TestCase.ConsumerLib.csproj.nuget.g.props

          dotnet test

  -
    matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - cmd: >-
          echo ---- build for Windows! ----

          echo %cd%

          dotnet --info

          cd demos\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin\Release\NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ..\..\modify-test-case-packages.patch

          dotnet build -c Debug

          cd %APPVEYOR_BUILD_FOLDER%\source\NuLink.Cli

          dotnet build -c Release

    test_script:
      - cmd: >-
          echo ---- test for Windows! ----

          echo USER-PROFILE: %UserProfile%

          echo %cd%

          cd %APPVEYOR_BUILD_FOLDER%\demos\NuLink.TestCase.Consumer

          dotnet restore

          dotnet %APPVEYOR_BUILD_FOLDER%\source\NuLink.Cli\bin\Release\netcoreapp2.1\dotnet-nulink.dll link -p NuLink.TestCase.FirstPackage -l %APPVEYOR_BUILD_FOLDER%\demos\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage.csproj

          dotnet build

          type NuLink.TestCase.ConsumerLib\obj\NuLink.TestCase.ConsumerLib.csproj.nuget.g.props

          dotnet test
