version: 0.1.{build}

image:
  - Ubuntu
  - Visual Studio 2017
configuration:
  - Release
for:
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - sh: >-
          echo ---- build for Linux! ----

          pwd

          dotnet --info

          cd demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin/Release/NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ../../modify-test-case-packages.patch

          dotnet build -c Debug

    test_script:
      - sh: >-
          echo ---- test for Linux! ----

          pwd

          cd ../../NuLink.TestCase.Consumer

          dotnet restore

          mv /home/appveyor/.nuget/packages/nulink.testcase.firstpackage/0.1.0-beta1/lib/netstandard2.0 /home/appveyor/.nuget/packages/nulink.testcase.firstpackage/0.1.0-beta1/lib/nulink-backup.netstandard2.0

          echo "ln -s $APPVEYOR_BUILD_FOLDER/demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage/bin/Debug/netstandard2.0 /home/appveyor/.nuget/packages/nulink.testcase.firstpackage/0.1.0-beta1/lib/netstandard2.0"

          ln -s $APPVEYOR_BUILD_FOLDER/demos/NuLink.TestCase.FirstPackage/NuLink.TestCase.FirstPackage/bin/Debug/netstandard2.0 /home/appveyor/.nuget/packages/nulink.testcase.firstpackage/0.1.0-beta1/lib/netstandard2.0

          ls -la /home/appveyor/.nuget/packages/nulink.testcase.firstpackage/0.1.0-beta1/lib/

          dotnet build

          cat NuLink.TestCase.ConsumerLib/obj/NuLink.TestCase.ConsumerLib.csproj.nuget.g.props

          dotnet test

  -
    matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - cmd: >-
          @echo ---- build for Windows! ----

          echo %cd%

          dotnet --info

          cd demos\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage

          dotnet build -c Release

          appveyor PushArtifact bin\Release\NuLink.TestCase.FirstPackage.0.1.0-beta1.nupkg

          git apply ..\..\modify-test-case-packages.patch

          dotnet build -c Debug

    test_script:
      - cmd: >-
          @echo ---- test for Windows! ----

          echo %cd%

          cd ..\..\NuLink.TestCase.Consumer

          dotnet restore

          cd C:\Users\appveyor\.nuget\packages\nulink.testcase.firstpackage\0.1.0-beta1\lib

          rename netstandard2.0 nulink-backup.netstandard2.0

          SET linkTargetDir=%APPVEYOR_BUILD_FOLDER%\demos\NuLink.TestCase.FirstPackage\NuLink.TestCase.FirstPackage\bin\Debug\netstandard2.0

          @echo --- linkTargetDir ---

          @echo %linkTargetDir%

          mklink /d netstandard2.0 $linkTargetDir

          dir

          cd %APPVEYOR_BUILD_FOLDER%\demos\NuLink.TestCase.Consumer

          dotnet build

          type NuLink.TestCase.ConsumerLib\obj\NuLink.TestCase.ConsumerLib.csproj.nuget.g.props

          dotnet test
