version: 0.1.{build}

image:
  - Ubuntu
  - Visual Studio 2017
configuration:
  - Release
for:
  -
    matrix:
      only:
        - image: Ubuntu
    build_script:
      - sh: echo ---- build for Linux! ----
    test_script:
      - sh: echo ---- test for Linux! ----
  -
    matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - ps: write-host "---- build for Windows! ----"
    test_script:
      - ps: write-host "---- test for Windows! ----"
